POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json

{
    "username": "sample",
    "email": "sample@gmail.com",
    "password": "123456789",
    "confirmPassword": "123456789"
}